### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by puppet33r** [AOCAWOL/BiomesYouGo#9]
There is a big cascading worldgen lag issue. I dont know if this is still up to date, but I think you should maybe take a look at this reddit post: https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/?ref_source=embed&ref=share

**Comment by AOCAWOL** [comment]
So I tried using the Journymap and seeing if BYG biomes aren't using the vanilla worldgen class correctly and they are? So I'm not really sure whats causing it rather than the fact my biomes override vanilla chunks (which is just how my mod works so). I'll be investigating it further :)

**Comment by Genetical** [comment]
I think the issue in this cirumstance is actually runaway world generation, I did some of my own research and during spawn preparation and loading new chunks after the player leaves spawn, the log is filled with these:

> [09:49:32] [Server thread/WARN] [FML]: Biomes You Go loaded a new chunk [7, 11] in dimension 0 (overworld) while populating chunk [6, 11], causing cascading worldgen lag.

Each chunk loads a new chunk when its populated up until

> [09:51:16] [Server thread/WARN] [FML]: Biomes You Go loaded a new chunk [4, 32] in dimension 0 (overworld) while populating chunk [2, 34], causing cascading worldgen lag.

34 chunks in one direction from spawn. This is caused by biomes such as the ancient forest in which the large trees spill out onto another chunk causing recursive generation of entire biomes or even more.

The best advise I can give is to set an abitrary limit to how far chunks can be generated from spawn if thats possible.

**Comment by AOCAWOL** [comment]
Thank you for this, unfortunately I really don't know how to fix it as my
mod uses Mcreator. Ill see if maybe making the trees in the ancient forest
smaller helps.

**Comment by Genetical** [comment]
I think that could help but it would be a shame because I really like the design of the trees. I also did a bit more investigation and there is an 8 block offset. The issue is that the trees are almost always bigger than 8 blocks and very close together so they will almost always cause cascading world generation.

Another cool graph showing excess world generation:
![image](https://user-images.githubusercontent.com/18619788/63598162-efd5d980-c5b6-11e9-9e3a-4ccbb78add05.png)

Maybe decrease biome size a little as well?
